### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by tiagoanleite** [hackjutsu/Lepton#122]
While searching for the download link for the app I've found that there is already another project hosted in GitHub called [Lepton](https://github.com/dropbox/lepton) from the guys over at [Dropbox](https://github.com/dropbox/).

Although they're completely different tools - one is a Gist client and the other is a compression tool - I don't know if it's a good idea to use the same name as another project.

**Comment by hackjutsu** [comment]
@tiagoanleite 

That's a interesting question, haha. I didn't realize dropbox has adopted this name for their project, since lepton is such a rare used word.

Lepton follows the naming convention of many other Electron projects to adopt the name of a type of physical particle, like [Electron](https://github.com/electron/electron), [Atom](https://github.com/atom/atom) and [Photon](https://github.com/connors/photon). And in physics, electron is the first known and most well-known lepton. In this sense, Lepton was chosen to honor the [Electron](https://github.com/electron/electron) framework which is used in this project.

Since it's legitimate and actually common for GitHub open source projects to have same or similar names, I would like to keep it as it is. 

I'm sure Dropbox must also have a strong reason to name image compression tool as lepton ;)

**Comment by tiagoanleite** [comment]
I didn't knew if you were aware, therefore I just wanted to warn you ;) 
Also, thanks for the explanation of the logic behind the name. I had no clue.
