### ISSUE TITLE
Editing area goes out of bound

### ISSUE THREAD

**Issue by zhouanbo** [hackjutsu/Lepton#126]
When first open the app, it's normal:

<img width="746" alt="screen shot 2017-03-14 at 8 53 26 pm" src="https://cloud.githubusercontent.com/assets/4448810/23928797/4c67cef2-08f8-11e7-80ce-452dbd6e13e4.png">

When I click on another tab and come back, the editing area extends to outside of the window, therefore hiding the edit and share buttons:

<img width="745" alt="screen shot 2017-03-14 at 8 51 19 pm" src="https://cloud.githubusercontent.com/assets/4448810/23928767/151ba702-08f8-11e7-8356-f8684fe57b30.png">

**Comment by hackjutsu** [comment]
@zhouanbo 

Thanks for reporting this issue. What do mean by saying "click on another tab"? Do you mean choosing another gist?

**Comment by zhouanbo** [comment]
Hi @hackjutsu,

Thanks for your attention! Yes, by saying "click on another tab", I mean choosing another gist. Extending the window doesn't really work because I have a really long code block in the mark down, it'll reveal more code by not enough.

<img width="934" alt="screen shot 2017-03-15 at 10 56 31 am" src="https://cloud.githubusercontent.com/assets/4448810/23954625/2fc30336-096e-11e7-9b8c-3aa97983e186.png">

Also pressing cmd+R to force electron re-render will work, but I think it's better to disable this debug function.

**Comment by hackjutsu** [comment]
@zhouanbo 

I met similar issue some time ago. It seems it happens only on markdown files, and goes away after re-rendering (when I noticed and clicked on `Command+Option+i`, it went away). 

I have no clues what could be the culprit at this moment, nor could I reproduce it on my side. It might be caused by the [react-split-pane](https://github.com/tomkp/react-split-pane) module that makes the gist panel resizable, or the Chromium itself (We used to see a Chromium rendering issue which was solved after updated to a newer version of Electron).

I might need more time to observe and understand this weird issue.

**Comment by hackjutsu** [comment]
@zhouanbo 

Since Lepton is an open source product, I would like everyone to be able to debug it (if they like), and provide as mush as debug information when reporting issues. (To be honest, I don't have the bandwidth to investigate all issues by myself~ )

Therefore, I'll keep these debug features enabled.
