### ISSUE TITLE
Pug (ex-Jade) is not highlighted

### ISSUE THREAD

**Issue by BroFox86** [hackjutsu/Lepton#135]
Pug (ex-Jade) is not highlighted on _preview page_

![2017-05-20 22 15 20](https://cloud.githubusercontent.com/assets/23554264/26278883/96c6d3b4-3dad-11e7-89c2-b145d507058b.png)

**Comment by hackjutsu** [comment]
Hi @BroFox86 , thanks for reporting:)

It looks like the suffix `.pug` is not recognized by `highlight.js` at this moment. We need to map it to `.jade` internally.

**Comment by hackjutsu** [comment]
It turns out that `Jade/Pug` is not supported in `highlight.js`. I'll close this issue.

@BroFox86 , If you feel the support is necessary, [highlight.js](https://github.com/isagalaev/highlight.js) might be a better place for a feature request. 



- https://github.com/isagalaev/highlight.js/issues/929
- https://github.com/isagalaev/highlight.js/issues/1159
