### ISSUE TITLE
[BUG] tag parse error

### ISSUE THREAD

**Issue by Cologler** [hackjutsu/Lepton#200]
![picpick-20170906-221448-001](https://user-images.githubusercontent.com/10906962/30116753-f200048c-9350-11e7-9eb1-b63497d9d9ae.png)

**Comment by hackjutsu** [comment]
Thanks for reporting.

Lepton uses the [twitter-text](https://github.com/twitter/twitter-text) for extracting twitter-style tags. A quick search shows that the ignorance of `-` seems to be intentional there(https://github.com/twitter/twitter-text/issues/88).

Maybe https://github.com/twitter/twitter-text/issues/88 is better place to discuss this issue :)

**Comment by Cologler** [comment]
But `-` is not a query parameter on github.

![picpick-20170906-235837-001](https://user-images.githubusercontent.com/10906962/30121841-55e75cee-935f-11e7-96dd-5d55a0c5b0da.png)

**Comment by hackjutsu** [comment]
It's just a policy how twitter-text extracts links from a string.  I believe it follows the same policy to extract hashtags too.

**Comment by hackjutsu** [comment]
@Cologler I forgot to mention we can actually make tags in this way, which accepts `-`.
```
[title] description #tags: tag1, tag2
```
https://github.com/hackjutsu/Lepton/issues/211
