### ISSUE TITLE
[bug] Putting the word 'begin' inside a comment inside a .sql gist sets its language to '#PLpgSQL'

### ISSUE THREAD

**Issue by web-surfer** [hackjutsu/Lepton#214]
If you make a gist with the **.sql** extension, and if you put the word '**begin**' inside a comment, the gist won't save as a SQL gist, but instead will save as 'PLpgSQL' language. Example:

`/*This is the beginning*/
SELECT *
FROM users;`

If you set the file name of this gist to a .sql extension, it won't save it as a SQL gist; it will save it as **PLpgSQL**.

**Comment by hackjutsu** [comment]
Lepton relies on GitHub v3 API to detect a gist's language. This sounds like a bug there. Since the API is not open-source, I doubt there is a way to report issues.

However, we can always explicitly specify a gist's language by placing `// vim: syntax=<your_language>` at the beginning of the gist. like
```
// vim: syntax=javascript
```

**Comment by web-surfer** [comment]
Thanks for that suggestion; it fixes the problem!
