### ISSUE TITLE
Cannot remove the first segment for each gist

### ISSUE THREAD

**Issue by eastingcw** [hackjutsu/Lepton#218]
win7-32位系统，每个 gist 里，每个代码段是按首字母 A-Z 顺序排列的，编辑的时候，首字母靠前的会跳到最上面，导致无法 remove第一个代码段

**Comment by hackjutsu** [comment]
For the convenience of English speaker, here is the Google translation: 

In win7-32 ​​bit system, each gist, each code segment is in alphabetical order A-Z, when editing, the first letter forward will jump to the top, resulting in can not remove the first code segment.

**Comment by hackjutsu** [comment]
@eastingcw 

I'll use English if you don't mind, so that if other people share the interest and they can join our discussion.

GitHub API doesn't allow creating an empty gist or removing all segments/files from an existing gist. I think that's the initiative to disable the "remove" button for the first segment/file. But you are right, the flow has flaws because it's legitimate for users to remove the first segment/file as long as they are not removing all of them.

**Comment by eastingcw** [comment]
So,it's a bug?you will fix it

**Comment by hackjutsu** [comment]
Me or anyone feel interested.

**Comment by eastingcw** [comment]
So great.I like it.

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/49d440064582126629bba97a469b473c9917cc2b
