### ISSUE TITLE
Sync failed: please check your network connection.

### ISSUE THREAD

**Issue by TimeBandit** [hackjutsu/Lepton#320]
* I'm seeing this issue on Ubuntu 18.04.1 LTS on my desktop.
* Still work on 16.0.4 LTS on my laptop.
* The upgrade to the latest LTS version of Ubuntu on my desktop somehow broke Lepton.
* The developer tools show no errors.
* I notice that Lepton has installed itself at `/snap/lepton/1`
* The only cache folder I could find was at `/home/[username]/.cache` but this did not contain a `Lepton` folder.

**Comment by hackjutsu** [comment]
@TimeBandit Thanks for reporting the issue. Which version of Lepton are you using? I'll see whether I can reproduce the issue on my side.

**Comment by TimeBandit** [comment]
@hackjutsu 
`lepton --version => 01`

**Comment by hackjutsu** [comment]
I actually have no idea where `lepton --version` command comes from. Maybe it's a snap command. Usually `command + ,` is the way to get Lepton version when the app is launched or inspect the logs. The scenario is tricky here because you cannot launch Lepton and there is no logs... But it's very likely to be v1.7.0. If snap doesn't work for you at this moment,  maybe have a try a for the AppImage format?
https://github.com/hackjutsu/Lepton/releases/tag/v1.7.0
