### ISSUE TITLE
.leptonrc file in Mac location

### ISSUE THREAD

**Issue by willsu88** [hackjutsu/Lepton#362]
Where is the .leptonrc file in Mac after I install Lepton through brew? I want to change the theme to dark.

**Comment by hackjutsu** [comment]
You can create it in `~/.leptonrc`.
https://github.com/hackjutsu/Lepton#customization

**Comment by jadczakd** [comment]
Created it like so, doesn't seem to take effect though.

**Comment by 2803media** [comment]
same here i also try the Applications folder where I put lepton

**Comment by 2803media** [comment]
it works, you need to remove any lines before
{

And put the file in the root under your mac username

**Comment by Integralist** [comment]
Wanted to say that this doesn't work for me.

I've placed the following config file in my home directory (`/Users/<name>/.leptonrc`)...

```
{
    "theme": "dark",
    "snippet": {
        "sorting": "created_at",
    },
}
```

I've restarted lepton app and nothing changes.

**Comment by Integralist** [comment]
Correction: it _does work_ but you need to ensure the JSON is valid (i.e. no trailing commas for the last properties).

So a _working example_ would be...

```json
{
    "theme": "dark",
    "snippet": {
        "sorting": "created_at"
    }
}
```

I did wonder about this when I saw the example JSON template linked to via the README but thought "well it must just work regardless because that's the template provided by the author".  

Guess not 🙂

**Comment by searock** [comment]
For those who create this config file from the TextEdit make sure your file name is saved as .leptonrc and not as .leptonrc.txt 

The file extension for txt is hidden and it might look like the file is .leptonrc, you can easily rename this from the terminal.
