### ISSUE TITLE
Question: how to zoom or increase font size

### ISSUE THREAD

**Issue by Integralist** [hackjutsu/Lepton#388]
#### Environment info
* OS: macOS
* App Version (`Command/Ctrl + ,`): Lepton v1.8.1

#### Description of the problem / feature request / question:

Question: my eyes are old and tired :-) how do I increase the font size?

Thanks!

**Comment by cosmo1024** [comment]
I believe we can increase them by ”cmd/ctrl +”, same as in Chrome browser.q

**Comment by hackjutsu** [comment]
I believe we can increase them by ”cmd/ctrl +”, same as in Chrome browser.

**Comment by Integralist** [comment]
> I believe we can increase them by ”cmd/ctrl +”, same as in Chrome browser.

OK so it seems this is only half true (for me at least).

Turns out I could use `Cmd -` to _decrease_ the size, and `Cmd 0` to reset it to a default size, but `Cmd +` didn't work to _increase_ the size! 

To increase the size I had to add 'Shift', so the actual key sequence is:

```
Cmd Shift +
```

**Comment by hackjutsu** [comment]
You are right, the shortcut is `Cmd Shift +`. This is interesting since there is mismatch between the the shortcut shown in the "View" menu and the actual one. Thanks for pointing this out.

![zoom_in_shortcut](https://user-images.githubusercontent.com/7756581/69503814-94c3c380-0ed2-11ea-991e-ddd6452a4bc3.jpg)
