### ISSUE TITLE
[macOS] Cannot open because the developer cannot be verified

### ISSUE THREAD

**Issue by mittalyashu** [hackjutsu/Lepton#401]
The more we know about your system and use case, the more easily and likely we can help.

Unable to install `leptop@1.8.2` on MacOS

#### Environment info
* OS: 10.15.2
* App Version: 1.8.2

#### If possible, provide a sample gist or screenshot:

<img width="488" alt="Screenshot 2020-01-27 at 2 17 13 PM" src="https://user-images.githubusercontent.com/29014463/73160713-bed27580-410f-11ea-8087-cb6a9f42c3c4.png">

**Comment by webtamizhan** [comment]
Same here, cannot open.

**Environment info:**

- OS: MacOs Catalina 10.15.2
- App version: 1.8.2

**Comment by hackjutsu** [comment]
Hi, pls enable Lepton in the security settings preference.

**Comment by we-taper** [comment]
Hi @hackjutsu ,

Should we consider adding a note about this inside the `README.md`?

**Comment by izikeros** [comment]
In some cases (e.g. company laptops) security configuration of macOS don't allow users to bypass gatekeeper (the way hinted in link shared by @hackjutsu ). It would be beneficial if this app could go through notarization process. Seems that it requires some effort but IMO app can benefit from broaden user-base due to better accessibility.

https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution
