### ISSUE TITLE
Login by GitHub token

### ISSUE THREAD

**Issue by DoneSpeak** [hackjutsu/Lepton#412]
I think it would be safer to allow the client to login with Github token instead of redirect to Github page to ask user to login with their GitHub account.

**Comment by GabrielNicolasAvellaneda** [comment]
@DoneSpeak @hackjutsu Is this the documentation related this new feature request?

**Comment by Spreeuw** [comment]
@hackjutsu I was looking at the code and it seems that internally the app is already using access tokens, is that correct? Would it be difficult to let the user choose between entering the access token or logging in? It would be quite useful because it would allow multiple people from a team access a single gist account without needing to share the login (which is against Github terms of service and can get you banned).

**Comment by hackjutsu** [comment]
https://github.com/hackjutsu/Lepton/commit/64b8d90c3be10b15b0d8bff0ba4fad65652808c1
