### ISSUE TITLE
activeGist changed after delete a gist

### ISSUE THREAD

**Issue by whtsky** [hackjutsu/Lepton#42]
![2017-02-03 17_23_47](https://cloud.githubusercontent.com/assets/876694/22586064/c136263e-ea35-11e6-92dd-a7b2accb3c76.gif)

As you can see, active gist changed after gist delete completes.

**Comment by hackjutsu** [comment]
Thanks. That's a good point. The culprit is the synchronization rather than the delete (The delete operation calls synchronization after sending the DELETE request).
https://github.com/hackjutsu/Lepton/blob/master/app/index.js
```javascript
function reSyncUserGists () {
  let state = reduxStore.getState()
  preSyncSnapshot = {
    activeGistTag: state.activeGistTag,
    activeGist: state.activeGist
  }
  updateUserGists(state.userSession.profile.login, state.accessToken)
}
```
The synchronization takes a snapshot for the state before the update, and tries to restore it once finishes. Based on the implementation available now, any operation during the synchronization will be ignored. You can observe the sync status by the progress bar under the profile image. If the previous activeGist is no longer valid, it falls back to the default one, in most cases, the first one in the selected category. We might need to avoid any operation during the synchronization.

This is something should be fixed.

**Comment by hackjutsu** [comment]
Should be fixed:https://github.com/hackjutsu/Lepton/commit/0a7f93101f1c64bca6ee8a672923ea35fdfd8c19

I'll include this fix in the next release. Please have a test then.
