### ISSUE TITLE
Create a VS Code extension of Lepton 

### ISSUE THREAD

**Issue by IkramHussainSiyam** [hackjutsu/Lepton#549]
# Please create a VS Code extension to integrate Lepton snippets.

### Features of this extension should be:
1. Create, edit, delete snippets
2. User can insert a snippet where his cursor is
3. User can download files which are saved in Lepton 
4. User can save a selected code block as a snippet.
5. User also can browse extensions inside VS Code in sidebar.

**Comment by hackjutsu** [comment]
I thought about the VSCode extension, but I believe it would be more convenient to use a GitHub Gist extension that interacts directly with the GitHub Gist APIs, rather than relying on a Lepton extension as an intermediary. You can simply include `[title] #tag1, #tag2` in the gist title, and Lepton will automatically parse and recognize these tags when the gist is synced locally.
