### ISSUE TITLE
The Escape item in menu doesn't work

### ISSUE THREAD

**Issue by wujysh** [hackjutsu/Lepton#63]
Menu: `Gist` -> `Escape`
Nothing will happen if this menu item is clicked.
Tough pressing `Esc` will close the popup windows (new/edit gist).
Perhaps, it is only broken on Linux? (I'm using Ubuntu 16.10.)

Besides, is it used to close the whole application?
If so, it is duplicated with menu item `Window` -> `Close`.
If not, what's its function?
Is it redundant and should be removed?

**Comment by hackjutsu** [comment]
In main.js, the `Esc` is registered as [a menu item](http://electron.atom.io/docs/api/menu/), so that it can emit the `exit-search` event and `exit-immersive-mode` event (in v1.1.0, which is not released) when pressed. 

```javascript
{
  label: 'Escape',
  accelerator: 'Escape',
  click: (item, mainWindow) => {
     mainWindow && mainWindow.send('exit-search')
     mainWindow && mainWindow.send('exit-immersive-mode')
  }
}
```

I have to admit the key-bindings in Lepton is awkward and pre-mature. Maybe there is a better way to bind the `Esc` without adding it the menu.  (The feature to dismiss the edit/new dialog by `Esc` comes with the Dialog component.)

There is a way to bind a key as a [global shortcut](https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md), which however overwrites the `Esc` in other apps. And we definitely don't want that.

**Comment by hackjutsu** [comment]
@dukewan might be an expert on this topic.

**Comment by wujysh** [comment]
@hackjutsu 
I think the `Escape` item in menu is confusing and should be removed.

As the gist new/edit popup can be closed by pressing `Esc`, the close behavior of search and immersive mode can be implemented without `Escape` menu item too? Need global shortcut of `Esc`?

Besides, close button `x` can be added on the popup windows.

**Comment by hackjutsu** [comment]
@wujysh Not a priority at this moment, but will address it in the future release.

**Comment by hackjutsu** [comment]
Change it to `Back to Normal Mode`

![image](https://cloud.githubusercontent.com/assets/7756581/23297101/fcc791a4-fa2c-11e6-874c-5d2c0436d5fb.png)
