### ISSUE TITLE
description template when creating gist

### ISSUE THREAD

**Issue by dukewan** [hackjutsu/Lepton#64]
It's better to auto generate the template for faster creating gist.

For example:
Set this as the default value for the input
```
[] #tags:
```

**Comment by wujysh** [comment]
Could the input box be expanded to fill in more text?
Split the title input into three inputs?
Support tag-selecting when `#` being pressed?

**Comment by hackjutsu** [comment]
@wujysh GitHub Gist server only supports the one-line input field.  Even if we can break it into multiple lines, they are still concatenated when submitted to Gist server, which makes it hard to restore it back to multi-lines after a sync.

**Comment by hackjutsu** [comment]
@dukewan 
I consider `[] #tags:` as an advanced topic. What if the users don't understand the template? Will it just confuses the users?

**Comment by wujysh** [comment]
@hackjutsu
I don't think it's difficult to restore back the title, description and tags.
`]` and `#tags:` are obvious characters to split the string. It's aim to improve user experience.
I don't know how to input tags either at first, just as #71.

**Comment by hackjutsu** [comment]
This might be a workaround at this moment. Will add more input fields in the future release.

![image](https://cloud.githubusercontent.com/assets/7756581/22719492/a54e352e-ed5a-11e6-8590-e711705b2827.png)

**Comment by wujysh** [comment]
@hackjutsu 
IMHO, description should better support Markdown.
I suggest It can be stored as a snippet file with specific filename (e.g. `0_description.md`) and display as description instead of a snippet. As well as the tags. 
(I'm afraid Markdown syntax will conflict with `#tags:`, or you can stored them all in the title field)
After implemented the local storage, the search issue can also be resolved.

**Comment by hackjutsu** [comment]
@wujysh 

Thank you for suggestion:) This is a good point, but I view this issue in a different way.

Lepton is a gist client to facilitate as well as encourage the use of gist, so its first design principle is to be compatible with GitHub's own web client rather than re-creating a new ecosystem. Bearing this in mind, I have the following rules for design:

1. A gist's information should be self-contained, which means it doesn't need an extra file to store its meta data, like the markdown style description or tags.
2. A gist's description section should have a self-described format, and maintain good readability even in plain text. So far, `[title] description #tags: tag1, tag2` is the best I have come up with.

In this way, **users have freedom to switch among Lepton, GitHub's web client or other better apps in the future**, without concerning about losing any data or having difficulties to understand Lepton's own mechanism. Sometimes, being conservative and doing less is in line with users' long term interest.

**Comment by wujysh** [comment]
@hackjutsu 
I understand and respect your opinion.
Hope to find a better way to enhance the title/description/tag input field.

**Comment by hackjutsu** [comment]
9d0cabc5c3d6b85886ed6a5e6075c217ec3418db
