### ISSUE TITLE
CodeMirror syntax highlight error

### ISSUE THREAD

**Issue by hackjutsu** [hackjutsu/Lepton#99]
It looks like CodeMirror tries to highlight anything that seems to be html.

![jietu20170210-120812](https://cloud.githubusercontent.com/assets/7756581/22843166/1b5c1ab8-ef8d-11e6-9140-9b1d030d7473.png)

https://gist.github.com/211179a4846abab9178a3b85cfb84ace

**Comment by hackjutsu** [comment]
We can disable all highlight to keep consistent.

**Comment by wujysh** [comment]
@hackjutsu 
This is caused by the `mode` setting of CodeMirror. If it is set correctly according to the code, its style will be fine. If not, while its auto mode detecting is not robust, highlighting could be wrong.
You can currently set `mode: 'plaintext'` to disable all highlighting. I'm still trying to implement changing mode according to filename.

**Comment by hackjutsu** [comment]
Thanks~ The syntax highlight for CodeMirror is a nice-to-have feature, but not a must-have. I might want to stick to plain text before this feature becomes robust.

**Comment by hackjutsu** [comment]
Fixed: https://github.com/hackjutsu/Lepton/commit/46abe43edd59650693bba1f961b16a905380cc0a
